# Generated by Django 2.0.3 on 2018-03-20 21:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('video', models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Raissa Arruda\\Desktop\\Django\\VideoOPENCV\\mysite\\static'), upload_to='media/videosenviados')),
            ],
        ),
    ]
