# Generated by Django 2.0.3 on 2018-05-04 15:39

import ckeditor.fields
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='db_video',
            name='video',
            field=models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Raissa Arruda\\Desktop\\Django\\teste-ferramentas-adaple\\VideoRTC\\mysite\\static'), upload_to='media/videosenviados'),
        ),
    ]
