# Generated by Django 2.0.5 on 2018-06-03 02:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20180504_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_video',
            name='video',
            field=models.FileField(default='media/none.mp4', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\raiss\\Documents\\Projetos\\testes\\VideoRTC\\mysite\\static'), upload_to='media/videosenviados'),
        ),
    ]
